server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WebService
    username: root
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: agc01075547865@gmail.com
    password: love2003
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: mybatis-mapper/*.xml
  configuration.map-underscore-to-camel-case: true